### ISSUE TITLE
ParameterError: Value for parameter CO2 missing.

### ISSUE THREAD

**Issue by sulekahraman** [ajwdewit/WOFOST_crop_parameters#1]
Using `YAMLCropDataProvider()`, getting this error when trying to run WOFOST. 
```ParameterError: Value for parameter CO2 missing.```

Inspecting the crop data, we can see that CO2 is indeed missing. Value for variable CO2 should be added to the param files here. 

```
crop_name = 'wheat'
variety_name = 'Winter_wheat_101'
cropd = YAMLCropDataProvider() # pulls from https://github.com/ajwdewit/WOFOST_crop_parameters
cropd.set_active_crop(crop_name, variety_name)
cropd.keys()
```
Output:
`dict_keys(['CO2EFFTB', 'CO2TRATB', 'CO2AMAXTB', 'TBASEM', 'TEFFMX', 'TSUMEM', 'IDSL', 'DLO', 'DLC', 'TSUM1', 'TSUM2', 'DTSMTB', 'DVSI', 'DVSEND', 'VERNBASE', 'VERNSAT', 'VERNDVS', 'VERNRTB', 'TDWI', 'RGRLAI', 'SLATB', 'SPA', 'SSATB', 'SPAN', 'TBASE', 'KDIFTB', 'EFFTB', 'AMAXTB', 'TMPFTB', 'TMNFTB', 'CVL', 'CVO', 'CVR', 'CVS', 'Q10', 'RML', 'RMO', 'RMR', 'RMS', 'RFSETB', 'FRTB', 'FLTB', 'FSTB', 'FOTB', 'PERDL', 'RDRRTB', 'RDRSTB', 'CFET', 'DEPNR', 'IAIRDU', 'IOX', 'RDI', 'RRI', 'RDMCR', 'NMAXLV_TB', 'NMAXRT_FR', 'NMAXST_FR', 'NMAXSO', 'NCRIT_FR', 'NRESIDLV', 'NRESIDST', 'NRESIDRT', 'TCNT', 'NFIX_FR', 'PMAXLV_TB', 'PMAXRT_FR', 'PMAXST_FR', 'PMAXSO', 'PCRIT_FR', 'PRESIDLV', 'PRESIDST', 'PRESIDRT', 'TCPT', 'KMAXLV_TB', 'KMAXRT_FR', 'KMAXST_FR', 'KMAXSO', 'KCRIT_FR', 'KRESIDLV', 'KRESIDST', 'KRESIDRT', 'TCKT', 'DVS_NPK_STOP', 'DVS_NPK_TRANSL', 'NLAI_NPK', 'NSLA_NPK', 'NPART', 'NLUE_NPK', 'NPK_TRANSLRT_FR', 'RDRLV_NPK'])`

**Comment by ajwdewit** [comment]
Dear Sule,

I see this comment rather late. Not sure if I responded to it already. CO2 is essentially a 'site' parameter not a crop parameter. so it is part of the SiteParameterProvider.

The only reason I can see that add a CO2 parameter to the crop parameter file is because the max assimilation rate (AMAXTB) is essentially tied to an atmospheric CO2 level when the value was measured. For most crops this is currently 360ppm. 
Allard
